# ApiKey for the Bot
apiKey: YourAPI
# chat channel id
channelId: YourChannelID

# The prefix for the Guilded users
prefixGuilded: "[Guilded User] %username%: "
# The prefix for the Minecrafter players
prefixMine: "%username%: "
# The prefix for the Bot
prefixCommand: "MC!"

# enable ip command
enableIpCommand: true
serverIp: "YourServerIP"
serverPort: "19132"
# enable players command
enablePlayerListCommand: true
# guilded command in Minecraft
guildedCommand: true
guildedCommandMessage: "Join our Guilded server at Â§e<put your invite here>Â§f!"

# Msg to send when the server is starting
isStartingMsg: true
startingMsg: "The server is starting, please wait..."
# Msg to send when the server is ready
isReadyMsg: true
readyMsg: "**âœ… The server is ready to play!**"
# Msg to send when the server is stopping
isStoppingMsg: true
stoppingMsg: "The server is stopping, please wait..."
# Msg to send when the server is stopped
isStoppedMsg: true
stoppedMsg: "**âŒ The server is stopped!**"
# enable join/leave messages to guilded
isJoinLeaveMsg: true
joinMsg: "**â• %username% has joined the server!**"
leaveMsg: "**â– %username% has left the server!**"
#enable death messages to guilded
isDeathMsg: true
deathMsg: "**ğŸ’€ %deathMsg%**"

# allow bots messages
allowBotMsg: true
# filtrer regex
# anti spam
messageFilterRegex: (?i)guilded.*?\..*?\/|http.*?\:.*?\/\/
messageFilterReplace: "<link>"